apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 3000
    name: http # important to have named ports for istio https://istio.io/docs/setup/kubernetes/prepare/requirements/
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
  - port: 80
    targetPort: 3003
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: users
spec:
  selector:
    app: users
  ports:
  - port: 80
    targetPort: 3001
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: orders
spec:
  selector:
    app: orders
  ports:
  - port: 80
    targetPort: 3002
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
spec:
  selector:
    app: shipping
  ports:
  - port: 80
    targetPort: 3005  
    name: http
---

########################### Deployments ###########################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: v1
  template:
    metadata:
      labels:
        app: frontend
        version: v1 
    spec:
      containers:
      - name: frontend
        image: basharlabadi/istio-demo.frontend:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
     
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
      version: v1
  template:
    metadata:
      labels:
        app: gateway
        version: v1
    spec:
      containers:
      - name: gateway
        image: basharlabadi/istio-demo.gateway:1.0.0
        imagePullPolicy: Always
        # resources:
        #   limits:
        #     memory: "256Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 3003
     
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
      version: v1
  template:
    metadata:
      labels:
        app: users
        version: v1
    spec:
      containers:
      - name: users
        image: basharlabadi/istio-demo.users:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
   
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
      version: v1
  template:
    metadata:
      labels:
        app: orders
        version: v1
    spec:
      containers:
      - name: orders
        image: basharlabadi/istio-demo.orders:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
   
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  labels:
    app: shipping
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping
      version: v1
  template:
    metadata:
      labels:
        app: shipping
        version: v1 
    spec:
      containers:
      - name: shipping
        image: basharlabadi/istio-demo.shipping:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3005 
    