# https://istio.io/docs/tasks/traffic-management/mirroring/
# advanced stuff : https://blog.christianposta.com/microservices/advanced-traffic-shadowing-patterns-for-microservices-with-istio-service-mesh/
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs.frontend
spec:
  hosts:
  - "*"
  gateways:
  - my-gateway
  http:
  - route:
    - destination:
        host: frontend
        port: 
          number: 80
        subset: v1
      weight: 100
    mirror:
        host: frontend
        port: 
          number: 80
        subset: v2