server.port: 3002

logging:
  level:
    reactor.ipc.netty.channel.ChannelOperationsHandler: DEBUG
    com.basharallabadi: TRACE
#    reactor.ipc.netty.http.server.HttpServer: DEBUG
#    reactor.ipc.netty.http.client: DEBUG
    root: INFO
#    io.reactivex.netty.protocol.http.client: DEBUG
#    io.netty.handler: DEBUG
#    io.netty.handler.proxy.HttpProxyHandler: DEBUG
#    io.netty.handler.proxy.ProxyHandler: DEBUG
#    org.springframework.web.reactive.function.client: DEBUG
#    reactor.ipc.netty.channel: DEBUG